CREATE TABLE "Order" (
  "id" SERIAL PRIMARY KEY,
  "gigId" INTEGER NOT NULL REFERENCES "Gig"("id") ON DELETE CASCADE,
  "buyerId" INTEGER NOT NULL REFERENCES "User"("id") ON DELETE CASCADE,
  "sellerId" INTEGER NOT NULL REFERENCES "User"("id") ON DELETE CASCADE,
  "status" TEXT NOT NULL DEFAULT 'pending',
  "dueDate" TIMESTAMP(3) NOT NULL,
  "notes" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
