-- CreateTable
CREATE TABLE "GigOrder" (
    "id" SERIAL PRIMARY KEY,
    "gigId" INTEGER NOT NULL REFERENCES "Gig"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    "buyerId" INTEGER NOT NULL REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    "amount" DOUBLE PRECISION NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'paid',
    "transactionId" INTEGER NOT NULL REFERENCES "Transaction"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
