ALTER TABLE "Gig" ADD COLUMN "clicks" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Gig" ADD COLUMN "orders" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Gig" ADD COLUMN "earnings" DOUBLE PRECISION NOT NULL DEFAULT 0;
