CREATE TABLE "ServiceAppointment" (
  "id" SERIAL PRIMARY KEY,
  "sellerId" INTEGER NOT NULL REFERENCES "User"("id") ON DELETE CASCADE,
  "buyerId" INTEGER REFERENCES "User"("id") ON DELETE SET NULL,
  "title" TEXT NOT NULL,
  "start" TIMESTAMP NOT NULL,
  "end" TIMESTAMP NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'booked',
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Task" (
  "id" SERIAL PRIMARY KEY,
  "creatorId" INTEGER NOT NULL REFERENCES "User"("id") ON DELETE CASCADE,
  "assigneeId" INTEGER REFERENCES "User"("id") ON DELETE SET NULL,
  "title" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "budget" DOUBLE PRECISION NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'open',
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
